# Site settings
title: Onion Galaxy
description: We are Onion Galaxy, a game development team formed by 21 students of the Master's Degree in AAA Videogames Development.
#remote_theme: nrandecker/particle
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
email: oniongalaxy.studio@gmail.com
github_username: OnionGalaxy

# Collections
collections:
  blog:
    output: true
    permalink: /:collection/:path/
  team:
    output: true
    permalink: /:collection/:path/

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
